module.exports = {
  userModels: require('./user.models'),
  fmtqikModels: require('./fmtqik.models'),
  commentModels: require('./comment.model'),
  stockModels: require('./stock.models'),
  newsModels: require('./news.model'),
  incomeStatementModels: require('./income_statement.models'),
  balanceSheetModels: require('./balance_sheet.model'),
  // cashFlowStatementModels: require('./cash_flow_statement.model'),
  individualNewModels: require('./individual_new.model'),
  financialStatementModels: require('./financial_statement.model'),
  dividendPolicyModels: require('./dividend_policy.model'),
  assetStatementsModels: require('./assetStatement.model'),
  balanceSheetLiabilitiesEquityModels: require('./balanceSheetLiabilitiesEquity.model'),
  incomeStatementsModels: require('./incomeStatement.model'),
  cashFlowStatementModels: require('./cashFlowStatement.model'),
  sentimentAnalysisModels: require('./sentiment_analysis.model'),
  bwibbuAllModels: require('./bwibbu_all.model'),
  stockDayAllModels: require('./stock_day_all.model'),
  googleNewsArticlesModels: require('./google_news_articles.model'),
  miIndexModels: require('./mi_index.model'),
  taiexModels: require('./taiex.model'),
  investmentTechModels: require('./investmentTech')
}
